source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BetterSegmentedControl_Example' do
  pod 'BetterSegmentedControl', :path => '../'
end

target 'BetterSegmentedControl_Tests' do
  pod 'BetterSegmentedControl', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
