source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BetterSegmentedControl_Example' do
  pod 'BetterSegmentedControl', :path => '../'
end

target 'BetterSegmentedControl_Tests' do
  pod 'BetterSegmentedControl', :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'
end
